language: c
script: make
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gSyktpK/vmVffxWmE7XtEDKVL+7RUuVgmxPWQ41jlnZ2MmzauiyvhgFFWb55gOXVRIXaRbDZ6Mb342xO4kLv1LefvrpdPxur8s9TGIxN7Nye2X+QX1q0Et3miLUd5r1RRusY2vBhF4Ufe3HUhS6cVaizh7vpk0npL5kf0PYusJI="

addons:
  coverity_scan:
    project:
      name: "justforfunfuntest/sandbox"
      description: "Build submitted via Travis CI"
    notification_email: justforfunfuntest@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
